server:
    port: 9008

spring:
    application:
        name: INVENTORY-SERVICE


eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://10.177.68.20:8761/eureka
    instance:
        hostname: 10.177.68.20