server:
  port: 9000

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
      - id: CUSTOMER-SERVICE
        uri: lb://CUSTOMER-SERVICE
        predicates:
          - Path=/customers/**
        filters:
          - name: CircuitBreaker
            args:
              name: CUSTOMER-SERVICE
              fallbackuri: forward:/customerServiceFallBack
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
          - Path=/departments/**
        filters:
          - name: CircuitBreaker
            args:
              name: DEPARTMENT-SERVICE
              fallbackuri: forward:/departmentServiceFallBack
      - id: MERCHANT-SERVICE
        uri: lb://MERCHANT-SERVICE
        predicates:
          - Path=/merchants/**
        filters:
          - name: CircuitBreaker
            args:
              name: MERCHANT-SERVICE
              fallbackuri: forward:/merchantServiceFallBack
      - id: PRODUCT-SERVICE
        uri: lb://PRODUCT-SERVICE
        predicates:
          - Path=/products/**
        filters:
          - name: CircuitBreaker
            args:
              name: PRODUCT-SERVICE
              fallbackuri: forward:/productServiceFallBack
      - id: CATEGORY-SERVICE
        uri: lb://CATEGORY-SERVICE
        predicates:
          - Path=/categories/**
        filters:
          - name: CircuitBreaker
            args:
              name: CATEGORY-SERVICE
              fallbackuri: forward:/categoryServiceFallBack
      - id: ORDERS-SERVICE
        uri: lb://ORDERS-SERVICE
        predicates:
          - Path=/orders/**
        filters:
          - name: CircuitBreaker
            args:
              name: ORDERS-SERVICE
              fallbackuri: forward:/ordersServiceFallBack
      - id: USERACTIVITY-SERVICE
        uri: lb://USERACTIVITY-SERVICE
        predicates:
          - Path=/userActivity/**
        filters:
          - name: CircuitBreaker
            args:
              name: USERACTIVITY-SERVICE
              fallbackuri: forward:/userActivityServiceFallBack
      - id: CART-SERVICE
        uri: lb://CART-SERVICE
        predicates:
          - Path=/carts/**
        filters:
          - name: CircuitBreaker
            args:
              name: CART-SERVICE
              fallbackuri: forward:/cartServiceFallBack
      - id: INVENTORY-SERVICE
        uri: lb://INVENTORY-SERVICE
        predicates:
          - Path=/inventories/**
        filters:
          - name: CircuitBreaker
            args:
              name: INVENTORY-SERVICE
              fallbackuri: forward:/inventoryServiceFallBack
      - id: API-DATA-JUNCTION
        uri: lb://API-DATA-JUNCTION
        predicates:
          - Path=/apiJunction/**
        filters:
          - name: CircuitBreaker
            args:
              name: API-DATA-JUNCTION
              fallbackuri: forward:/apiJunctionServiceFallBack
#      - id: SOLR-SERVICE
#              uri: lb://SOLR-SERVICE
#              predicates:
#                - Path=/solr/**
#              filters:
#                - name: CircuitBreaker
#                  args:
#                    name: SOLR-SERVICE
#                    fallbackuri: forward:/solrServiceFallBack
      

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost