server:
    port: 9009

spring:
    application:
        name: API-DATA-JUNCTION


eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        hostname: localhost